backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "media" #images and other (small!) downloadable resources, no videos

collections:
  - name: "tools"
    label: "Tools"
    folder: "tools"
    create: true
    fields:
      - {label: "Identifier", name: "identifier", hint: "The identifier of the tool exactly as it is known by CLARIAH Tool Discovery, set either this or group name. For internal use.", widget: "string"}
      - {label: "Group", name: "group", hint: "The group or suite name exactly as known by CLARIAH Tool Discovery, set either this or identiftier. For internal use.", widget: "string"}
      - {label: "Title", name: "title", widget: "string"} #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter
  - name: "data"
    label: "Data"
    folder: "data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string" } #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter
  - name: "standards"
    label: "Standards"
    folder: "standards"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string" } #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter


