backend:
  name: github
  repo: CLARIAH/ineo-content
  branch: master # Branch to update (optional; defaults to master)
  site_domain: clariah.github.io
  #site_domain: ineo-content.netlify.com #this was a bit of a process to setup via netlify.com: https://cnly.github.io/2018/04/14/just-3-steps-adding-netlify-cms-to-existing-github-pages-site-within-10-minutes.html


media_folder: "media" #images and other (small!) downloadable resources, no videos

collections:
  - name: "tools"
    label: "Tools"
    folder: "src/tools"
    create: true
    fields:
      - {label: "Identifier", name: "identifier", hint: "The identifier of the tool exactly as it is known by CLARIAH Tool Discovery, set either this or group name. For internal use.", widget: "string", required: false}
      - {label: "Group", name: "group", hint: "The group or suite name exactly as known by CLARIAH Tool Discovery, set either this or identiftier. For internal use.", widget: "string", required: false }
      - {label: "Title", name: "title", widget: "string"} #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter
  - name: "data"
    label: "Data"
    folder: "src/data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: false  } #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter
  - name: "standards"
    label: "Standards"
    folder: "src/standards"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: false } #filename will derive from this (slugified)
      - {label: "Body", name: "body", widget: "markdown"} #actual markdown context after the front matter


